plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()

    reports {
        junitXml.required = true
        junitXml.outputLocation = layout.buildDirectory.dir('reports/junit')
    }
}
